[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Jan Philipp Tebernum <jan.tebernum@pm.me>"]

[workspace]
members = [
  "crates/stm32g474re",
  "crates/stm32f767zi"
]
resolver = "2"

